using ModCreator.Attributes;
using ModCreator.Commons;
using System.Collections.Generic;

namespace ModCreator.Models
{
    [SetterAspect]
    public class ModConfElement : AutoNotifiableObject
    {
        public string FileName { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public string VarType { get; set; }
        public bool Shown { get; set; } = true;
        public bool Disabled { get; set; } = false;
        public bool Required { get; set; } = false;
        public bool ReadOnly { get; set; } = false;
        public bool Unique { get; set; } = false;
        public bool ModEventParam { get; set; } = false;
        public List<string> Options { get; set; } = [];
        public string Value { get; set; }
        public string Separator { get; set; }
        public List<string> SubProperties { get; set; } = [];
        public bool IsAutoGeneratedId { get; set; } = false;
    }
}
