using ModCreator.Attributes;
using ModCreator.Commons;
using ModCreator.Helpers;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;

namespace ModCreator.Models
{
    public class PatternFileDisplay
    {
        public string FileName { get; set; }
        public int FrozenColumns { get; set; }
        public ObservableCollection<PatternElement> Elements { get; set; } = [];
        public ObservableCollection<PatternElement> DisplayElements { get; set; } = [];
        public ObservableCollection<RowDisplay> Rows { get; set; } = [];
        public ObservableCollection<PatternElement> FrozenDisplayElements => 
            DisplayElements.Take(Math.Min(FrozenColumns, DisplayElements.Count)).ToOC();
        public ObservableCollection<PatternElement> ScrollableDisplayElements => 
            DisplayElements.Skip(Math.Min(FrozenColumns, DisplayElements.Count)).ToOC();

        public void AddRow(int autoGenMin = 1000000, int autoGenMax = 9999999)
        {
            var newRow = new Dictionary<string, string>();
            foreach (var element in Elements)
            {
                if (element.IsAutoGeneratedId)
                {
                    newRow[element.Name] = GenerateId(element.Name, autoGenMin, autoGenMax);
                }
                else
                {
                    newRow[element.Name] = element.Value ?? string.Empty;
                }
            }
            Rows.Add(new RowDisplay(newRow, Elements, DisplayElements, FrozenColumns));
        }

        private string GenerateId(string elementName, int min, int max)
        {
            var existingIds = new HashSet<int>();
            foreach (var row in Rows)
            {
                if (row.RowData.TryGetValue(elementName, out var value) && int.TryParse(value, out var id))
                {
                    existingIds.Add(id);
                }
            }

            var random = new Random();
            int newId;
            int attempts = 0;
            do
            {
                newId = random.Next(min, max + 1);
                attempts++;
            } while (existingIds.Contains(newId) && attempts < 1000);

            return newId.ToString();
        }

        public void RemoveRow(RowDisplay row)
        {
            Rows.Remove(row);
        }
    }
}
