using ModCreator.Attributes;
using ModCreator.Commons;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace ModCreator.Models
{
    public class PatternElement : ValidatedModel
    {
        public string Name { get; set; }
        public string Type { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public string VarType { get; set; }
        public bool Enable { get; set; } = true;
        public bool Required { get; set; } = false;
        public ObservableCollection<ModConfValue> Options { get; set; } = new ObservableCollection<ModConfValue>();
        public string Value { get; set; }
        public string Separator { get; set; }
        public List<PatternElement> SubElements { get; set; } = new List<PatternElement>();
        public PatternElement ParentElement { get; set; }
        public string ElementFormat { get; set; }
        public bool IsDynamicOptions => ((ElementFormat?.StartsWith("[") ?? false) && (ElementFormat?.EndsWith("]") ?? false)) 
            || ((ElementFormat?.StartsWith("#") ?? false) && (ElementFormat?.EndsWith("#") ?? false));
        public bool IsMultiSelect => (ElementFormat?.StartsWith("#") ?? false) && (ElementFormat?.EndsWith("#") ?? false);
        public bool IsAutoGenerated => !string.IsNullOrEmpty(ElementFormat) && !IsDynamicOptions;
        public bool IsSubElement => ParentElement != null;
        public bool IsReadOnly { get; set; } = false;
    }
}
