using ModCreator.Attributes;
using ModCreator.Commons;
using System.Collections.ObjectModel;

namespace ModCreator.Models
{
    public class PatternElement : ValidatedModel
    {
        public ModConfElement Element { get; set; }
        public string ElementName { get; set; }
        public string Name { get; set; }
        public string DefaultType { get; set; }
        public string Type
        {
            get
            {
                if (!string.IsNullOrEmpty(ElementFormat))
                {
                    if (ElementFormat.StartsWith("[") && ElementFormat.EndsWith("]"))
                        return "combo";
                    if (ElementFormat.StartsWith("#") && ElementFormat.EndsWith("#"))
                        return "multicombo";
                    if (ElementFormat.StartsWith("@") && ElementFormat.EndsWith("@"))
                        return "resource";
                }
                return DefaultType;
            }
        }
        public string ResourceFolder
        {
            get
            {
                if (!string.IsNullOrEmpty(ElementFormat) && ElementFormat.StartsWith("@") && ElementFormat.EndsWith("@"))
                {
                    return ElementFormat.Trim('@');
                }
                return string.Empty;
            }
        }
        public string Label { get; set; }
        public string Description { get; set; }
        public string VarType { get; set; }
        public bool Shown { get; set; } = true;
        public bool Disabled { get; set; } = false;
        public bool ReadOnly { get; set; } = false;
        public bool Required { get; set; } = false;
        public bool Unique { get; set; } = false;
        public bool ModEventParam { get; set; } = false;
        public string RefDocs { get; set; }
        public ObservableCollection<ModConfValue> Options { get; set; } = [];
        public string Value { get; set; }
        public string Separator { get; set; }
        public ObservableCollection<PatternElement> SubElements { get; set; } = [];
        public PatternElement ParentElement { get; set; }
        public string ElementFormat { get; set; }
        public bool IsDynamicOptions => !string.IsNullOrEmpty(ElementFormat) && Type != "textbox";
        public bool IsMultiSelect => !string.IsNullOrEmpty(ElementFormat) && Type == "multicombo";
        public bool IsAutoGenerated => !string.IsNullOrEmpty(ElementFormat) && Type == "textbox";
        public bool IsAutoGeneratedId { get; set; } = false;
        public bool IsSubElement => ParentElement != null;
        public bool IsReadOnly => Disabled || ReadOnly || IsAutoGenerated;
        public bool IsDisabled => Disabled;
    }
}
