using ModCreator.Attributes;
using ModCreator.Commons;
using ModCreator.Helpers;
using System.Collections.Generic;
using System.Linq;

namespace ModCreator.Models
{
    [SetterAspect]
    public class RowElementBinding : AutoNotifiableObject
    {
        private Dictionary<string, string> Row { get; set; }
        private List<PatternElement> AllElements { get; set; }
        private List<RowElementBinding> AllBindings { get; set; }
        public PatternElement Element { get; set; }

        public string XValue
        {
            get => Row.ContainsKey(Element.Name) ? Row[Element.Name] : string.Empty;
            set
            {
                var oldValue = XValue;
                if (Row.ContainsKey(Element.Name))
                    Row[Element.Name] = value;
                else
                    Row.Add(Element.Name, value);

                if (oldValue != value)
                {
                    ProcessElementFormat();
                }
            }
        }

        public RowElementBinding(Dictionary<string, string> row, PatternElement element, List<PatternElement> allElements = null, List<RowElementBinding> allBindings = null)
        {
            Row = row;
            AllElements = allElements;
            AllBindings = allBindings;
            Element = element;
        }

        private void ProcessElementFormat()
        {
            if (AllElements == null || AllBindings == null)
                return;

            foreach (var element in AllElements.Where(e => !string.IsNullOrEmpty(e.ElementFormat)))
            {
                if (element.IsAutoGenerated)
                {
                    var generatedValue = PatternHelper.ProcessAutoGenValue(element.ElementFormat, Row);
                    if (Row.ContainsKey(element.Name))
                        Row[element.Name] = generatedValue;
                    else
                        Row.Add(element.Name, generatedValue);

                    var targetBinding = AllBindings.FirstOrDefault(b => b.Element.Name == element.Name);
                }
            }
        }
    }
}
