using ModCreator.Businesses;
using ModCreator.Models;
using ModCreator.WindowData;
using System;
using System.Linq;
using System.Windows;
using System.IO;

namespace ModCreator.Windows
{
    public partial class PatternSelectorWindow : CWindow<PatternSelectorWindowData>
    {
        // Business logic handler
        private PatternSelectorWindowCodeGenerationBusiness _codeGenerationBusiness;

        public override void OnLoad()
        {
            base.OnLoad();

            // Initialize business
            _codeGenerationBusiness = new PatternSelectorWindowCodeGenerationBusiness(WindowData, this);

            var projectEditorWindow = Owner as ProjectEditorWindow;
            if (projectEditorWindow.WindowData.Project != null)
            {
                WindowData.ProjectPath = projectEditorWindow.WindowData.Project.ProjectPath;
            }
        }

        private void Save_Click(object sender, RoutedEventArgs e)
        {
            var projectEditorWindow = Owner as ProjectEditorWindow;
            var projectPath = projectEditorWindow?.WindowData?.Project?.ProjectPath;

            if (_codeGenerationBusiness.SavePatternFiles(projectPath))
            {
                projectEditorWindow.WindowData.LoadConfFiles();
            }
        }

        private void Cancel_Click(object sender, RoutedEventArgs e)
        {
            DialogResult = false;
            Close();
        }

        private void AddRow_Click(object sender, RoutedEventArgs e)
        {
            if (sender is System.Windows.Controls.Button button && button.Tag is PatternFileDisplay file)
            {
                file.AddRow(WindowData.AutoGeneratedIdRangeMin, WindowData.AutoGeneratedIdRangeMax);
            }
        }

        private void RemoveRow_Click(object sender, RoutedEventArgs e)
        {
            if (sender is System.Windows.Controls.Button button && button.Tag is RowDisplay row)
            {
                var file = WindowData.DisplayFiles.FirstOrDefault(f => f.Rows.Contains(row));
                file?.RemoveRow(row);
            }
        }

        private void ComboBox_DropDownOpened(object sender, EventArgs e)
        {
            if (sender is System.Windows.Controls.ComboBox comboBox && comboBox.Tag is RowElementBinding binding)
            {
                WindowData.LoadDynamicOptionsForElement(binding.Element);
            }
        }

        private void MultiSelectComboBox_DropDownOpened(object sender, EventArgs e)
        {
            if (sender is Controls.MultiSelectComboBox multiCombo && multiCombo.Tag is RowElementBinding binding)
            {
                WindowData.LoadDynamicOptionsForElement(binding.Element);
            }
        }

        private void RefDocs_Click(object sender, RoutedEventArgs e)
        {
            if (sender is System.Windows.Controls.Button button && button.Tag is PatternElement element)
            {
                if (!string.IsNullOrEmpty(element.RefDocs))
                {
                    var sampleConfsPath = Path.GetFullPath(Path.Combine(Constants.RootDir, "3385996759", "SampleConfs"));
                    var filePath = Path.Combine(sampleConfsPath, element.RefDocs);

                    if (File.Exists(filePath))
                    {
                        var refDocsWindow = new PatternRefDocsWindow
                        {
                            Owner = this,
                            FilePath = filePath
                        };
                        refDocsWindow.ShowDialog();
                    }
                    else
                    {
                        MessageBox.Show($"Reference documentation file not found:\n{filePath}", "File Not Found", MessageBoxButton.OK, MessageBoxImage.Warning);
                    }
                }
            }
        }

        private void SelectResource_Click(object sender, RoutedEventArgs e)
        {
            if (sender is System.Windows.Controls.Button button && button.Tag is RowElementBinding binding)
            {
                // Extract ResourceType from ResourceFolder (format: Type:Folder/Folder or just Type)
                var resourceFolder = binding.Element.ResourceFolder;
                var parts = resourceFolder.Split(':');
                var resourceTypeString = parts[0];
                var folder = parts[1];

                // Parse string to GameResourceType enum
                if (!Enum.TryParse<Enums.GameResourceType>(resourceTypeString, true, out var resourceType))
                {
                    resourceType = Enums.GameResourceType.Other;
                }

                var resourceWindow = new PatternResSelectWindow
                {
                    Owner = this,
                    ResourceType = resourceType,
                    ResourceFolder = folder
                };

                if (resourceWindow.ShowDialog() == true)
                {
                    binding.XValue = resourceWindow.SelectedResourcePath;
                }
            }
        }
    }
}
